services:
  order:
    build:
      context: .
      dockerfile: ../order/Dockerfile
      target: development
    command: npm run start:dev order
    env_file:
      - ../order/.env
    depends_on:
      - dev-db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3005:3005'
  bff:
    build:
      context: .
      dockerfile: ../bff/Dockerfile
      target: development
    command: npm run start:dev bff
    env_file:
      - ../bff/.env
    depends_on:
      - order
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8888:8888'
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
        

 
  

