
GET http://localhost:8888/order-kafka/billing
###

GET http://localhost:8888/order/all
###

GET http://localhost:8888/order/random-create
###

GET http://localhost:8888/orders/random-create
###

POST http://localhost:4001/orders/5
Accept: application/json
###

DELETE  http://localhost:4001/orders/64d5ff31f81a753124112317

