
GET http://localhost:4001/orders
###

GET http://localhost:4001/orders/random-create
###

POST http://localhost:4001/orders/6
Accept: application/json
###

DELETE  http://localhost:4001/orders/64d9e99cb168813f9736f3ae

