
GET http://localhost:4001/orders
###

GET http://localhost:4001/orders/random-create
###

POST http://localhost:4001/orders/5
Accept: application/json
###

PATCH  http://localhost:4001/orders/64d49619a0b2f0c44d58bab5

